spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          #Git仓库，在公司里，配置仓储应该独立，与代码仓库分开
          uri: https://github.com/lqr20000325/1708d_rikao0426.git
          #uri: https://gitee.com/zhanggm1002/zhanggm-springcloud-demo-1708d.git
          #uri: https://gitee.com/zhanggm1002/springcloud-demo-0325.git
          search-paths:
            - configfiles
          #默认拉取配置Git分支
          default-label: master
          #如果你的Git不公开的，需要设置用户名和密码
          #username: zhangsan
          #password: 123456
      #从哪个分支去拉去配置文件
      label: spring-cloud-config
server:
  port: 8888
  #给配置中心统一加访问前缀，在网关配置路由
  #servlet:
    #context-path: /config/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/